name: ci-check

on: [push, pull_request]

jobs:
  lint_build_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - run: yarn install

    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build-all
    - name: Test
      run: yarn test
