name: ci-release

on:
  workflow_run:
    workflows: ["ci-check"]
    branches: [release]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn clean

      - name: Publish npm package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |  
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

      - name: Generate document
        env:
          INPUT_TOKEN: ""
        run: yarn docs
      - name: Deploy document
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs

  notification:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Send build result to slack channel
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_WEBHOOK: ${{ secrets.ORG_SLACK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: Powered by CasperDash