#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy to Github pages

on:
  push:
    branches:
      - master

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn install
    - run: yarn docs

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.2.1
      with:
        branch: gh-pages
        folder: docs
